# Generated by Django 3.2 on 2022-08-10 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='honey/updates')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(null=True, upload_to='honey/updates'),
        ),
    ]
