# Generated by Django 3.2 on 2022-08-14 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_auto_20220810_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='honey/updates')),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='honey/updates')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='update',
            name='dates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
