# Generated by Django 3.2 on 2022-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0003_auto_20220814_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
