# Generated by Django 3.2 on 2022-08-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0004_auto_20220815_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='Title',
            new_name='title',
        ),
    ]
